// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCard: typeof import('element-plus/es')['ElCard'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElPopover: typeof import('element-plus/es')['ElPopover'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}

export {};
